name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["CI Workflow for backend"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: v1

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -f Dockerfile -t finalgo:${{ env.IMAGE_TAG }} .

      - name: Tag Docker image
        run: |
          docker tag finalgo:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/finalgo:${{ env.IMAGE_TAG }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/finalgo:${{ env.IMAGE_TAG }}
