name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["CI Workflow for backend"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -f Dockerfile -t finalgo:V${{ github.run_number }} .

      - name: Tag Docker image
        run: |
          docker tag finalgo:V${{ github.run_number }} ${{ secrets.DOCKER_HUB_USERNAME }}/finalgo:V${{ github.run_number }}

      - name: Run Trivy security scan on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'finalgo:V${{ github.run_number }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy image SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image-results.sarif

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/finalgo:V${{ github.run_number }}
