
name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["CI Workflow for backend"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: v2
      REGISTRY: ghcr.io  
      REPOSITORY: ${{ github.repository }}


    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication

      - name: Build the Docker image
        run: |
          docker build -f Dockerfile -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/finalgo:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/finalgo:${{ env.IMAGE_TAG }}
